project:
  type: website
  output-dir: docs

website:
  title: ""
  favicon: "./images/favicon.ico"
  twitter-card: true
  site-url: https://stats9.github.io/
  sidebar: 
    style: "docked"
    border: true
    alignment: "left"
    contents: 
      - text: About
        file: about.qmd
      - text: BlueSky
        file: BlueSky.qmd
      - text: P~value~
        file: Pvalue.qmd
      - text: Anvoa-SS
        file: Anova-SS.qmd
    tools:
      - icon: envelope-at
        menu: 
          - text: report a problem
            url: mailto:habibezati88@gmail.com
          - text: Suggestion
            url: mailto:habibezati88@gmail.com
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    border: true
    background: "#303c54"
    center: "Copyright 2023, Habib Ezatabadi"
    left:
      - icon: github
        href: https://github.com/stats9
      - icon: linkedin
        href: https://www.linkedin.com/in/habib-ezzat-abadi-pour-23300abb/
      - icon: envelope-at
        href: mailto:habibezati88@gmail.com
  navbar:
    tools:
      - icon: github
        href: https://github.com/stats9
      - icon: linkedin
        href: https://www.linkedin.com/in/habib-ezzat-abadi-pour-23300abb/
      - icon: envelope-at
        href: mailto:habibezati88@gmail.com
    logo: "./images/logo_image.jpg"
    left:
      - text: Home
        file: index.qmd
      - text: About
        file: about.qmd
      - text: BlueSky
        file: BlueSky.qmd
      - text: P~value~
        file: Pvalue.qmd
      - text: Anova-SS
        file: Anova-SS.qmd

format:
  html:
    theme: flatly
    mainfont: Nexa
    linkcolor: red
    css: styles.css
    toc: true
